# Generated by Django 4.0.4 on 2022-05-19 23:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='header_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=blog.models.get_header_image_filepath),
        ),
    ]
